import {
  FaFileInvoiceDollar,
  FaBuilding,
  FaBookOpen,
  FaChartLine,
  FaShieldAlt,
  FaMoneyCheckAlt,
  FaBriefcase,
  FaFileAlt,
} from 'react-icons/fa'

export const services = [
  {
    id: 'individual-tax',
    title: 'Individual Tax Preparation',
    icon: FaFileInvoiceDollar,
    description: 'Accurate and efficient personal tax return preparation. We maximize your deductions and ensure compliance with federal and state regulations.',
    details: [
      'Federal and NY State returns',
      'Itemized deduction optimization',
      'Investment and rental income',
      'Self-employment income',
      'Multi-state filing',
    ],
  },
  {
    id: 'business-tax',
    title: 'Business Tax Returns',
    icon: FaBuilding,
    description: 'Comprehensive business tax services for LLCs, S-Corps, C-Corps, and partnerships. We help you stay compliant and minimize your tax liability.',
    details: [
      'LLC, S-Corp, C-Corp returns',
      'Partnership filings',
      'Estimated tax planning',
      'Business deduction strategies',
      'Quarterly compliance',
    ],
  },
  {
    id: 'bookkeeping',
    title: 'Bookkeeping & Accounting',
    icon: FaBookOpen,
    description: 'Keep your finances organized year-round with professional bookkeeping services. Accurate records make tax time stress-free.',
    details: [
      'Monthly reconciliation',
      'Expense categorization',
      'Financial statement preparation',
      'Accounts payable/receivable',
      'Year-end reporting',
    ],
  },
  {
    id: 'tax-planning',
    title: 'Tax Planning & Advisory',
    icon: FaChartLine,
    description: 'Strategic tax planning to help you make informed decisions throughout the year. Reduce your tax burden with proactive guidance.',
    details: [
      'Year-round tax strategy',
      'Retirement planning optimization',
      'Entity structure advice',
      'Tax-efficient investing',
      'Life event tax planning',
    ],
  },
  {
    id: 'irs-representation',
    title: 'IRS Representation',
    icon: FaShieldAlt,
    description: 'Facing an audit or IRS notice? We represent you before the IRS and help resolve tax issues professionally and efficiently.',
    details: [
      'Audit representation',
      'IRS notice response',
      'Payment plan negotiation',
      'Offer in compromise',
      'Tax lien/levy resolution',
    ],
  },
  {
    id: 'payroll',
    title: 'Payroll Services',
    icon: FaMoneyCheckAlt,
    description: 'Reliable payroll processing for small businesses. We handle calculations, filings, and compliance so you can focus on your business.',
    details: [
      'Weekly/bi-weekly/monthly payroll',
      'Payroll tax filings',
      'W-2 and 1099 preparation',
      'Direct deposit setup',
      'New hire reporting',
    ],
  },
  {
    id: 'business-formation',
    title: 'New Business Formation',
    icon: FaBriefcase,
    description: 'Starting a business in New York? We guide you through entity selection, registration, and getting set up for tax compliance from day one.',
    details: [
      'Entity type selection (LLC, Corp, etc.)',
      'EIN registration',
      'State and local registration',
      'Initial tax setup',
      'Compliance checklist',
    ],
  },
  {
    id: 'amended-returns',
    title: 'Prior Year & Amended Returns',
    icon: FaFileAlt,
    description: 'Need to fix a previous return or file for past years? We handle amended and prior year returns to get you back on track.',
    details: [
      'Amended federal and state returns',
      'Prior year filings (up to 6 years)',
      'Correcting filing errors',
      'Claiming missed deductions',
      'IRS correspondence follow-up',
    ],
  },
]
